package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import cn.hehe9.persistent.entity.VideoSource;

@Repository
public interface VideoSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int insert(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int insertSelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    VideoSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VideoSource record);
    
    List<VideoSource> findBy(Map<String, Object> params);
}