package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import cn.hehe9.persistent.entity.VideoEpisode;

@Repository
public interface VideoEpisodeMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	int insert(VideoEpisode record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	int insertSelective(VideoEpisode record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	VideoEpisode selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(VideoEpisode record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video_episode
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(VideoEpisode record);

	/**
	 * 根据条件, 查询记录
	 * @param params
	 * @return
	 */
	List<VideoEpisode> findBy(Map<String, Object> params);
}