package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import cn.hehe9.persistent.entity.Video;

@Repository
public interface VideoMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	int insert(Video record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	int insertSelective(Video record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	Video selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Video record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table video
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Video record);

	/**
	 * 根据条件, 查询简要信息
	 * @param params
	 * @return
	 */
	public List<Video> findBriefBy(Map<String, Object> params);

	/**
	 * 根据条件, 查询视频信息
	 * @param params
	 * @return
	 */
	public List<Video> findBy(Map<String, Object> params);
}